### ISSUE TITLE
Fix sample(Low-Level API) code error

### ISSUE THREAD

**Issue by taroooyan** [sacloud/libsacloud#79]
Sample(Low-Level API)の一部のコードが動作しないものを修正する。

## 実行環境
- macOS 10.12.3
- Go 1.7.4

## 現状
READMEに書かれているSample(Low-Level API)のコードの実行でコンパイルエラーがでる。
```
./main.go:81: cannot use hostName (type string) as type *string in assignment
./main.go:82: cannot use password (type string) as type *string in assignment
./main.go:84: cannot use script.Resource.ID (type int64) as type string in argument to diskConf.AddNote
```

## 解決案

変更前(81行~84行)
```
    diskConf.HostName = hostName
    diskConf.Password = password
    diskConf.SSHKey.PublicKey = sshPublicKey
    diskConf.AddNote(script.ID)
```

変更後(81行~84行)
```
    diskConf.HostName = &hostName
    diskConf.Password = &password
    diskConf.SSHKey.PublicKey = sshPublicKey
    diskConf.AddNote(string(script.ID))
```

## 変更による問題
実行すると83行目の`diskConf.SSHKey.PublicKey = sshPublicKey`で以下のエラーで落ちる
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x2a56]
```

この行に関係するものをコメントアウトして実行すると84行目の`diskConf.AddNote(string(script.ID))`で以下のエラーで落ちる
```
panic: strconv.ParseInt: parsing "�": invalid syntax
```

この行に関係するものをコメントアウトして実行すると落ちることなく実行された。
最終的なコード [Gist](https://gist.github.com/taroooyan/5c6ba64259b946d0f3e75a4556ada39f)
そこでこれらの項目がきちんと動作するようにする。

**Comment by yamamoto-febc** [comment]
Hi @taroooyan 

コントリビューションありがとうございます:+1:
READMEのサンプルコードが古かったので修正しました。

修正コミット： 2ffe32e82a90381ef6852b9ce24f0cce4d4e4709

FYI: サンプルコードは`api/doc_test.go`にてExampleテストとして実装しています。  
このためテストコードのコンパイルエラーはgo test実行時に検出可能です。

https://github.com/sacloud/libsacloud/blob/master/api/doc_test.go#L189
